# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NTAFilter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'AlamofireImage', '~> 3.3'
  # Pods for NTAFilter

  target 'NTAFilterTests' do
    inherit! :search_paths
    # Pods for testing
  end
	
end
